export const oblivionQuotes = [
    "I heard a rumor that you're an idiot. Any truth to that?",
    "he looks like a bit of a dandy",
    "When you're ready to get eviscerated",
    "Ni ni ni ni ni ni ni ni ni ni ni ni ni ni",
    "WHY. WON'T. YOU. DIE?",
    "HELP! SOMEONE'S BEEN MURDERED!!",
    "Look at the muscles on you!",
    "I’m not sure I’d want a discount spell...",
    "Stop right there criminal scum",
    "Are you the Count? No? THEN GO AWAY!!!!!!",
    "Are you the Count? Yes? You're a liar. You don't even look like a Count.",
    "I'm Otumeel. But I didn't do anything. Really. It wasn't me. Hahaha! No! Really! It wasn't me! Never!",
    "Okay, okay! I'll tell you! It is so great! I sneak into people's houses, take things off their tables and shelves, and put them into barrels! Hahaha! Isn't that rich? They think the things are stolen, but no! They are right there! They just don't know!",
    "I've fought mudcrabs more fearsome than you!",
    "I am sick of Orcs coming in here and giving me the business. 'Oooh, Bugak got a book store. Oooh, Bugak's a sissy scroll-scribbler!",
    "BY AZURA! BY AZURA! BY AZURA! IT'S YOU, THE GRAND CHAMPION, STANDING HERE NEXT TO ME!",
    "why am I in prison?",
    "Dear brother, I don't spread rumors... I create them!",
    "Well ain't you just the high tom titty?",
    "You're the Gray Fox! You're under arrest for… for… for all kinds of stuff! You're wanted dead or alive. I'm choosing dead.",
    "This is the part where you lie down and BLEED TO DEATH!",
    "I hear the fighters guild is looking to recruit",
    "Oh it's you...Hi...",
    "Someone really ought to put up a railing. That happens all the time.",
    "Oh wait can I do that one again",
    "BREAK THE LAW ON MY WATCH?",
    "YOU THERE! S T O P!",
    "STOP RIGHT THERE CRIMINAL SCUM",
    "You smell like death. Been conjuring up dead things?",
    "HELP ! There’s a psychopath on the loose",
    "What's the matter?! Getting tired?",
    "Have you heard of the high elves?",
    "Hey look everybody, I'm talking to a fly! Buzz, buzz, buzz.",
    "YOU'RE SLOWER THAN A PREGNANT COW!",
    "Blow away, wind bag",
    "Not funny, not even a little bit",
    "gal bursten it.",
    "Fribble in the Findoo!",
    "Fribble! Just fribble!",
    "Payday! Let’s roll",
    "Killed and ate a bosmer there once, but it made me sick. Saw Lord Sheogorath in the vomitus, so that's alright. Here to sacrifice? A limb would be nice.",
    "What did you do that for? Are you some kind of maniac?!",
    "Home is where you hang your enemy's head!",
    "I’ll not have anything to do with you, BEGONE!",
    "THEN PAY WITH YOUR BLOOD!!"
]